FROM ubuntu
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
WORKDIR /home

RUN apt-get update && apt-get upgrade --yes
RUN DEBIAN_FRONTEND='noninteractive' apt-get install --yes ffmpeg gcc gfortran git imagemagick python3-dev python3-pip tar wget

# MINICONDA SOFTWARE
RUN wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b
RUN rm Miniconda3-latest-Linux-x86_64.sh

# BASICS PYTHON APIs FOR DATA SCIENCE
RUN conda install jupyterlab matplotlib numpy pandas scikit-learn scipy seaborn sympy

# FILES I/O : GRIB & NETCDF
# - http://xarray.pydata.org/en/stable/installing.html
RUN conda install -c conda-forge cfgrib nc-time-axis netCDF4 rasterio xarray

# GEOGRAPHICAL MANIPULATIONS, PLOTS AND INTERACTIVE MAP
# - https://python-visualization.github.io/folium/
# - https://geopandas.org/install.html
# - https://scitools.org.uk/cartopy/docs/latest/installing.html#installing
RUN conda install -c conda-forge folium
RUN conda install -c conda-forge geopandas
RUN conda install -c conda-forge cartopy

# METEOROLOGICAL SIMULATIONS :
# - https://pypi.org/project/climlab/
RUN conda install -c conda-forge climlab

# THIRD PART SCRIPTS (N.O.A.A) :
RUN wget ftp://ftp.cpc.ncep.noaa.gov/wd51we/fast_downloading_grib/get_inv.pl
RUN wget ftp://ftp.cpc.ncep.noaa.gov/wd51we/fast_downloading_grib/get_grib.pl
RUN chmod +x get_inv.pl
RUN chmod +x get_grib.pl

# TO RUN INTERACTIVE MODE
CMD ["jupyter", "lab", "--allow-root", "--ip=*", "--no-browser", "--port=8080"]

# --------------------------------------------------------------------------------
#
# INSTALLATION :
#
# $ docker build -t julien/pylab .
#
#
# RUN INTERACTIVE MODE :
#
# $ docker run -p 8080:8080 -v C:/Users/julie/OneDrive/Documents/DOCKER/share:/home julien/pylab
#
# --------------------------------------------------------------------------------
 